### ISSUE TITLE
[Feature]: 为群聊中的不同用户的消息添加对应的名字/标签

### ISSUE THREAD

**Issue by a86296007** [RockChinQ/LangBot#613]
### 这是一个？

新功能

### 详细描述

如题，目前来说当bot在一个群聊中运行时，其会将所有群友发送的消息都视作同一个用户来进行对话，那么可否在输入每个群员发送的内容时，于消息前方附加上其个人信息（群名片、QQ号等）呢？这样的话，辅以相应的情景预设，群聊中的对话也许会更有效率一点？

**Comment by RockChinQ** [comment]
这个目前无法实现，OpenAI的api不支持自定义role

**Comment by a86296007** [comment]
> 这个目前无法实现，OpenAI的api不支持自定义role

直接以文本的形式插入到聊天文字前方也不可以吗？

举例的话，假如群员 aaaa 说了一句话 bbbbccccdddd，目前来说会直接给AI发送"bbbbccccdddd"，但能否将发送的内容变成"aaaa: bbbbccccdddd"这样，再使用特定的预设prompt让AI认人呢？

**Comment by a86296007** [comment]
> 直接以文本的形式插入到聊天文字前方也不可以吗？

仔细想了想，感觉可以做成一个插件

**Comment by RockChinQ** [comment]
这个做不了，因为主流的AI接口都不支持区分用户，需要prompt工程，可以自己写个插件实现一下。
