### ISSUE TITLE
[Feature]: 使用HTTP适配器时INFO刷屏

### ISSUE THREAD

**Issue by murasamme** [RockChinQ/LangBot#641]
### 这是一个？

现有功能优化

### 详细描述

模块预测：yirimirai
适配器：HTTPAdapter
日志级别：logging.INFO
问题现象：
![log](https://github.com/RockChinQ/QChatGPT/assets/52225526/1c9fde51-fe5f-4c71-8d2b-0d750e384a21)

情况描述：
使用HTTPAdapter适配器时，yirimirai的INFO消息会不停打印刷屏
修改日志级别为logging.WARN可以屏蔽，但是与mirai的消息交互以及api调用等INFO也被屏蔽掉

建议：
可以把http轮询的INFO放到日志DEBUG等级里，或者添加其他参数控制轮询INFO是否开启

**Comment by RockChinQ** [comment]
YiriMirai 适配器已于 3.4.0 移除，仍需使用 mirai 请使用 mirai 协议转 onebot 协议的中间件。
