### ISSUE TITLE
[Feature]: 强烈建议把!reload命令加回来

### ISSUE THREAD

**Issue by touyamakaze** [RockChinQ/LangBot#698]
### 这是一个？

现有功能优化

### 详细描述

3.0版本，!reload插件热加载的功能去掉了，
插件修改后（用户自己开发插件或者动态修改config等文件代码）每次都要重启整个项目，对于服务器上后台挂项目的情况很不友好。

**Comment by RockChinQ** [comment]
3.4.0 热重载随着webui回来了：https://docs.langbot.app/webui/system.html#%E7%83%AD%E9%87%8D%E8%BD%BD
