### ISSUE TITLE
[Bug]:python3.9中typing库的 | 操作符不支持

### ISSUE THREAD

**Issue by setwhite** [RockChinQ/LangBot#895]
### 消息平台适配器

Nakuru（go-cqhttp）

### 运行环境

Ubuntu python3.9.12

### QChatGPT版本

v3.3.1

### 异常情况

python3.9，typing库的 | 操作符不支持
报错TypeError: unsupported operand type(s) for |: '_UnionGenericAlias' and '_UnionGenericAlias'

QChatGPT-3.3.1.1/pkg/provider/entities.py中：
content: typing.Optional[list[ContentElement]] | typing.Optional[str] = None

QChatGPT-3.3.1.1/pkg/core/entities.py中：
resp_messages: typing.Optional[list[llm_entities.Message]] | typing.Optional[list[mirai.MessageChain]] = []

用typing.Union改写后正常运行

**Comment by RockChinQ** [comment]
现在不支持3.9了，最低要求python 3.10.1。
