### ISSUE TITLE
[Feature]: 啥时候把log改成UTF-8每次都看着特殊符号报错好难受

### ISSUE THREAD

**Issue by sanxianxiaohuntun** [RockChinQ/LangBot#927]
### 这是一个？

现有功能优化

### 详细描述

啥时候把log改成UTF-8每次都看着特殊符号报错好难受

**Comment by sanxianxiaohuntun** [comment]
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f92f' in position 50: illegal multibyte sequence
Call stack:

**Comment by RockChinQ** [comment]
master已经修好了，过几天发版包含，实在急的话可以直接clone最新代码

**Comment by RockChinQ** [comment]
3.4.0.1 已发。
