### ISSUE TITLE
[Feature]: 请求支持Openai和Anthropic的新模型

### ISSUE THREAD

**Issue by Tigrex-Dai** [RockChinQ/LangBot#931]
### 这是一个？

现有功能优化

### 详细描述

希望可以添加Openai的o1模型和Claude的Haiku3.5模型支持！
btw我看claude的模型都有一个claude-xxxx-latest的版本可以用，不知道能不能用于自动更新模型

**Comment by RockChinQ** [comment]
已更新，重启即可自动拉取。
