### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by Garrise** [RockChinQ/LangBot#937]
### 插件名称

YoutubeAnalysis

### 插件代码库地址

https://github.com/Garrise/LangBot_Plugin_YoutubeAnalysis

### 插件简介

识别群聊里的YouTube视频链接并返回视频预览内容

**Comment by RockChinQ** [comment]
感谢贡献！已添加到[star集](https://github.com/stars/RockChinQ/lists/qchatgpt-%E6%8F%92%E4%BB%B6)
