### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by Garrise** [RockChinQ/LangBot#941]
### 插件名称

LangBot_Plugin_YoutubeAnalysis

### 插件代码库地址

https://github.com/Garrise/LangBot_Plugin_YoutubeAnalysis

### 插件简介

支持油管视频链接解析
（抱歉之前操作有误，请重新添加插件，谢谢，并去掉我fork的别人的插件：https://github.com/Garrise/LangBot_Plugin_BilibiliAnalysis）

**Comment by RockChinQ** [comment]
感谢贡献！
