### ISSUE TITLE
[Bug]: dify无法上传图片

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [RockChinQ/LangBot#948]
### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 运行环境

docker

### LangBot 版本

3.4.1.1

### 异常情况

图片无法上传
![image](https://github.com/user-attachments/assets/353ea7a5-84ac-4810-9bc9-f731e3c4afff)
![d9a4c4c8307762cfda4ff79a9fb270fd](https://github.com/user-attachments/assets/22fe8d0f-4691-4f2f-b1aa-c62eb06d97bf)
![41e3484f0003fe4643858cbe19a2203a](https://github.com/user-attachments/assets/c54a116b-4ead-471a-89f1-0cb004ac5082)

**Comment by RockChinQ** [comment]
把控制台输出贴出来

**Comment by RockChinQ** [comment]
已发布在 v3.4.1.2
