### ISSUE TITLE
[Bug]: 无法使用dify agent应用

### ISSUE THREAD

**Issue by AlanBacker** [RockChinQ/LangBot#951]
### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 运行环境

Debian 11

### LangBot 版本

v3.4.1.1

### 异常情况

在正确配置provider.json（至少是按照文档的）后
我试图调用接入到dify的agent（本报告中agent的名称为"Gemini-QQ"）后无法正常调用
![image](https://github.com/user-attachments/assets/9d66d9ba-aa75-4ac8-9aff-f80e3e08be7c)
![image](https://github.com/user-attachments/assets/a7602d6d-5195-4987-b394-1e0791f16b2e)
![image](https://github.com/user-attachments/assets/0731a9a3-3c8f-46cf-90fe-f568f5eb7147)

**Comment by RockChinQ** [comment]
已在新版修复，需要根据文档重新填写配置文件。
